name: pull
on: push
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create report file
        run: git clone https://github.com/MotorolaMobilityLLC/kernel-msm.git -b MMI-U1TCS34.22-64-6-1
      - name: Commit report
        run: |
          git switch -c master1
          git config --global user.name 'ghazzor'
          git config --global user.email '127341071+ghazzor@users.noreply.github.com'
          git commit -am "Automated report"
          git push
